@echo off
setlocal

echo Starting file deletion process...

REM Define the list of file names to be deleted
set "files_to_delete=UI_HordeIcon-round UI_JailersTower_Defense UI_JailersTower_Offense UI_JailersTower_Utility UI_jailerstower-scenario-deathcounter UI_RankedPvP_01_Small UI_RankedPvP_02_Small UI_RankedPvP_03_Small UI_RankedPvP_04_Small UI_RankedPvP_05_Small UI_RankedPvP_06_Small UI_RankedPvP_07_Small UI_AllianceIcon-round INV_TortollanSeekers INV_TalanjisExpedition INV_LegionCircle_Cache_ArgussianReach INV_LegionCircle_Cache_ArmyoftheLight INV_LegionCircle_Cache_CourtofFarnodis INV_LegionCircle_Cache_DreamWeavers INV_LegionCircle_Cache_HightmountainTribes INV_LegionCircle_Cache_KirinTor INV_LegionCircle_Cache_Legionfall INV_LegionCircle_Cache_NightFallen INV_LegionCircle_Cache_nightmareraid INV_LegionCircle_Cache_Valajar INV_LegionCircle_Cache_Warden INV_LegionCircle_Faction_ArgussianReach INV_LegionCircle_Faction_ArmyoftheLight INV_LegionCircle_Faction_CourtofFarnodis INV_LegionCircle_Faction_DreamWeavers INV_LegionCircle_Faction_HightmountainTribes INV_LegionCircle_Faction_KirinTor INV_LegionCircle_Faction_Legionfall INV_LegionCircle_Faction_NightFallen INV_LegionCircle_Faction_Valarjar INV_LegionCircle_Faction_Warden INV_LegionCircle_ParagonCache_ArgussianReach INV_LegionCircle_ParagonCache_ArmyoftheLight INV_LegionCircle_ParagonCache_Legionfall INV_Faction_HordeWarEffort_Round INV_Faction_HordeWarfront_Round_HighmountainTauren INV_Faction_HordeWarfront_Round_MagharOrc INV_Faction_AllianceWarEffort_Round INV_Faction_AllianceWarfront_Round_DarkIronDwarf INV_Faction_AllianceWarfront_Round_LightforgedDraenei INV_Faction_AllianceWarfront_Round_VoidElf INV_Faction_Championsofazeroth_Round INV_Faction_HordeWarEffort_Round INV_Faction_HordeWarfront_Round_HighmountainTauren INV_Faction_HordeWarfront_Round_MagharOrc INV_Faction_HordeWarfront_Round_Nightborne INV_Faction_HordeWarfront_Round_ZandalariTroll INV_Faction_OrderofEmbers_Round INV_Faction_ProudmooreAdmiralty_Round INV_Faction_Stormswake_Round INV_Faction_TalanjisExpedition_Round INV_Faction_TortollanSeekers_Round INV_Faction_Voldunai_Round INV_Faction_WarResources_Round INV_Faction_ZandalariEmpire_Round"

REM Loop through each file name and delete the file
for %%f in (%files_to_delete%) do (
    if exist "%%f.*" (
        echo Deleting %%f.*...
        del /Q "%%f.*"
    ) else (
        echo File %%f.* not found.
    )
)

echo File deletion process completed.

:end
pause
